
const menu = [
  {
    id: 1,
    title: "Express Kahvaltı",
    category: "Kahvaltılıklar",
    price: 35,
    img: "img/express.jpg",
    desc: `Enfes Doyurucu BOL Kahvaltı.`,
    
  },
  {
    id: 2,
    title: "Tek Kişilik Tabak",
    category: "Kahvaltılıklar",
    price: 45,
    img: "img/tek.jpg",
    desc: `Tek Kişilik Kahvaltı Tabağı. `,
  },
  {
    id: 3,
    title: "Börekli Kahvaltı",
    category: "Kahvaltılıklar",
    price: 55,
    img: "img/boreklikahvaltı.jpg",
    desc: `Börekli Kahvaltı Tabağı`,
  },
  {
    id: 4,
    title: "Delfino Kahvaltı Tabağı",
    category: "Kahvaltılıklar",
    price: 60,
    img: "img/lüxkahvaltı.jpg",
    desc: `Delfino Kahvaltı Tabağı İle Lezzeti Doruklarda Yaşayın. `,
  },
  {
    id: 5,
    title: "Serpme Kahvaltı",
    category: "Kahvaltılıklar",
    price: 129,
    img: "img/2kısılıkkahvaltı.jpg",
    desc: `Serpme Kahvaltının Tadını Çıkartın`,
  },
  {
    id: 6,
    title: "Sıcak Simit Tabağı",
    category: "Kahvaltılıklar",
    price: 30,
    img: "img/sıcaksımıttabagı.jpg",
    desc: `Sıcak Simitin Tadını Çıkartın`,
  },
  {
    id: 7,
    title: "Kol Böreği",
    category: "Kahvaltılıklar",
    price: 20,
    img: "img/kol.jpg",
    desc: `Kıymalı,Peynirli,Patatesli`,
  },
  {
    id: 8,
    title: "Su Böreği",
    category: "Kahvaltılıklar",
    price: 20,
    img: "img/su.jpg",
    desc: `Sıcak Ve Taze Su Böreği`,
  },
  {
    id: 9,
    title: "Gül Böreği",
    category: "Kahvaltılıklar",
    price: 20,
    img: "img/gül.jpg",
    desc: `Sıcak Ve Taze Gül Böreği.`,
  },
  {
    id: 10,
    title: "Sahanda Yumurta",
    category: "Omlet Ve Menemen",
    categoryname: "Omlet Ve Menemen",
    price: 20,
    img: "img/sahanda.jpg",
    desc: `Sahanda Sucuklu 24TL , Sahanda Kaşarlı 23TL , Sahanda Kaşarlı 23TL , Sahanda Kavurmalı 30TL , Sahanda Karışık 30TL`,
  },
  {
    id: 11,
    title: "Omletler",
    category: "Omlet Ve Menemen",
    price: 20,
    img: "img/omlet.jpg",
    desc: `Sade Omlet 20TL , Kaşarlı Omlet 23TL , Sucuklu Omlet 25TL , Sebzeli Omlet 30TL , Kavurmalı Omlet 35TL`,
  },
  {
    id: 12,
    title: "Menemen",
    category: "Omlet Ve Menemen",
    price: 30,
    img: "img/menemen.jpg",
    desc: `Sade Menemen 30TL , Kaşarlı Menemen 34TL , Sucuklu Menemen 36TL , Karışık Menemen 38TL , Kavurmalı Menemen 45TL`,
  },
  {
    id: 13,
    title: "Mıhlama",
    category: "Omlet Ve Menemen",
    price: 25,
    img: "img/mıhlama.jpg",
    desc: ``,
  },
  {
    id: 14,
    title: "Günün Çorbası",
    category: "Aperatifler",
    price: 18,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 15,
    title: "Günün Menüsü",
    category: "Aperatifler",
    price: 40,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 16,
    title: "Yumurtalı Ekmek",
    category: "Aperatifler",
    price: 25,
    img: "img/yumurta.jpg",
    desc: ``,
  },
  {
    id: 17,
    title: "Sosis Tabağı",
    category: "Aperatifler",
    price: 35,
    img: "img/sosistabagı.jpg",
    desc: ``,
  },
  {
    id: 18,
    title: "Delfino Tabağı",
    category: "Aperatifler",
    price: 50,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 19,
    title: "Paçanga Böreği",
    category: "Aperatifler",
    price: 30,
    img: "img/paçanga.jpg",
    desc: ``,
  },
  {
    id: 20,
    title: "Soğan Halkası",
    category: "Aperatifler",
    price: 30,
    img: "img/soganhalkası.jpg",
    desc: ``,
  },
  {
    id: 21,
    title: "Parmak Patates",
    category: "Aperatifler",
    price: 25,
    img: "img/parmakpatates.jpg",
    desc: ``,
  },
  {
    id: 22,
    title: "Elma Dilim Patates",
    category: "Aperatifler",
    price: 30,
    img: "img/elmapatates.jpg",
    desc: ``,
  },
  {
    id: 23,
    title: "Çıtır Tavuk Parçaları",
    category: "Aperatifler",
    price: 40,
    img: "img/çıtırtavuk.jpg",
    desc: ``,
  },
  {
    id: 24,
    title: "Nugget",
    category: "Aperatifler",
    price: 35,
    img: "img/nugget.jpg",
    desc: ``,
  },
  {
    id: 25,
    title: "Karışık Pizza",
    category: "Aperatifler",
    price: 45,
    img: "img/karışıkpizza.jpg",
    desc: `Orta Boy`,
  },
  {
    id: 26,
    title: "Mantı",
    category: "Aperatifler",
    price: 40,
    img: "img/mantı.jpg",
    desc: ``,
  },
  {
    id: 27,
    title: "Ton Balıklı Sandviç",
    category: "Sandviç",
    price: 40,
    img: "img/tonbalıklı.jpg",
    desc: ``,
  },
  {
    id: 28,
    title: "Karışık Sandviç",
    category: "Sandviç",
    price: 30,
    img: "img/karışıksandviç.jpg",
    desc: ``,
  },
  {
    id: 29,
    title: "Tavuklu Sandviç",
    category: "Sandviç",
    price: 35,
    img: "img/tavuklusandviç.jpg",
    desc: ``,
  },
  {
    id: 30,
    title: "Köfteli Sandviç",
    category: "Sandviç",
    price: 50,
    img: "img/köftelisandviç.jpg",
    desc: ``,
  },
  {
    id: 31,
    title: "Beyaz Peynirli Sandviç",
    category: "Sandviç",
    price: 25,
    img: "img/beyazpeynirli.jpg",
    desc: ``,
  },
  {
    id: 32,
    title: "Kaşarlı Tost",
    category: "Tost",
    price: 25,
    img: "img/kaşarlıtost.jpg",
    desc: ``,
  },
  {
    id: 33,
    title: "Sucuklu Tost",
    category: "Tost",
    price: 28,
    img: "img/sucuklutost.jpg",
    desc: ``,
  },
  {
    id: 34,
    title: "Beyaz Peynir Domates Tost",
    category: "Tost",
    price: 25,
    img: "img/beyazpeynirlidomates.jpg",
    desc: ``,
  },
  {
    id: 35,
    title: "Karışık Tost",
    category: "Tost",
    price: 32,
    img: "img/karısıktost.jpg",
    desc: ``,
  },
  {
    id: 36,
    title: "Kavurmalı Tost",
    category: "Tost",
    price: 35,
    img: "img/kavurmalıtost.jpg",
    desc: ``,
  },
  {
    id: 37,
    title: "Ayvacık Tostu",
    category: "Tost",
    price: 35,
    img: "img/ayvalıktost.jpg",
    desc: ``,
  },
  {
    id: 38,
    title: "Kaşarlı Gözleme",
    category: "Gözleme",
    price: 27,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 39,
    title: "Sucuklu Gözleme",
    category: "Gözleme",
    price: 28,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 40,
    title: "Peynirli Gözleme",
    category: "Gözleme",
    price: 27,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 41,
    title: "Patatesli Gözleme",
    category: "Gözleme",
    price: 27,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 42,
    title: "Kavurmalı Gözleme",
    category: "Gözleme",
    price: 35,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 43,
    title: "Kıymalı Gözleme",
    category: "Gözleme",
    price: 35,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 44,
    title: "Karışık Gözleme Gözleme",
    category: "Gözleme",
    price: 38,
    img: "img/kaşarlıgözleme.jpg",
    desc: ``,
  },
  {
    id: 45,
    title: "Tavuk Sote",
    category: "Ana Yemekler",
    price: 50,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 46,
    title: "Güveçte Kaşarlı Tavuk Sote",
    category: "Ana Yemekler",
    price: 55,
    img: "img/kaşarlıtavuksote.jpg",
    desc: ``,
  },
  {
    id: 47,
    title: "Güveçte Kaşarlı Et Sote",
    category: "Ana Yemekler",
    price: 80,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 48,
    title: "Köri Soslu Tavuk",
    category: "Ana Yemekler",
    price: 55,
    img: "img/körisoslu.jpg",
    desc: ``,
  },
  {
    id: 49,
    title: "Mantarlı Tavuk Sote",
    category: "Ana Yemekler",
    price: 55,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 50,
    title: "Kremalı Mantarlı Tavuk",
    category: "Ana Yemekler",
    price: 55,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 51,
    title: "Tavuk Pirzola Bonfile",
    category: "Ana Yemekler",
    price: 55,
    img: "img/tavukbonfile.jpg",
    desc: ``,
  },
  {
    id: 52,
    title: "Viyana Schinitzel",
    category: "Ana Yemekler",
    price: 45,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 53,
    title: "Et Sote",
    category: "Ana Yemekler",
    price: 80,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 54,
    title: "Fajita Chicken",
    category: "Ana Yemekler",
    price: 80,
    img: "img/fajita.jpg",
    desc: ``,
  },
  {
    id: 55,
    title: "Fajita Steak",
    category: "Ana Yemekler",
    price: 90,
    img: "img/fajitaet.jpg",
    desc: ``,
  },
  {
    id: 56,
    title: "Izgara Kasap Köfte",
    category: "Ana Yemekler",
    price: 55,
    img: "img/köfte.jpg",
    desc: ``,
  },
  {
    id: 57,
    title: "Kaşarlı Kasap Köfte",
    category: "Ana Yemekler",
    price: 58,
    img: "img/kaarlıköfte.jpg",
    desc: ``,
  },
  {
    id: 58,
    title: "Izgara Piliç Şiş",
    category: "Ana Yemekler",
    price: 50,
    img: "img/ızgarapiliç.jpg",
    desc: ``,
  },
  {
    id: 59,
    title: "Izgara Et Çöp Şiş",
    category: "Ana Yemekler",
    price: 75,
    img: "img/ızgaraet.jpg",
    desc: ``,
  },
  {
    id: 60,
    title: "Izgara Steak",
    category: "Ana Yemekler",
    price: 90,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 61,
    title: "Karışık Izgara",
    category: "Ana Yemekler",
    price: 130,
    img: "img/karışıkızgara.jpg",
    desc: ``,
  },
  {
    id: 62,
    title: "DELFİNO Burger",
    category: "Burgerler",
    price: 45,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 63,
    title: "Steak Burger",
    category: "Burgerler",
    price: 65,
    img: "img/steakburger.jpg",
    desc: ``,
  },
  {
    id: 64,
    title: "Mini Burger",
    category: "Burgerler",
    price: 27,
    img: "img/miniburger.jpg",
    desc: ``,
  },
  {
    id: 65,
    title: "Cheese Burger",
    category: "Burgerler",
    price: 37,
    img: "img/cheeseburger.jpg",
    desc: ``,
  },
  {
    id: 66,
    title: "DELFİNO Tavuk Burger",
    category: "Burgerler",
    price: 40,
    img: "img/.jpg",
    desc: ``,
  },{
    id: 67,
    title: "Tavuk Burger",
    category: "Burgerler",
    price: 30,
    img: "img/tavukburger.jpg",
    desc: ``,
  },
  {
    id: 68,
    title: "Mini Tavuk Burger",
    category: "Burgerler",
    price: 00,
    img: "img/tavukburger.jpg",
    desc: ``,
  },
  {
    id: 69,
    title: "Tavuk Cheese Burger",
    category: "Burgerler",
    price: 40,
    img: "img/cheeseburger.jpg",
    desc: ``,
  },
  {
    id: 70,
    title: "Fettucine Alfredo",
    category: "Makarnalar",
    price: 50,
    img: "img/fettucine.jpg",
    desc: ``,
  },
  {
    id: 71,
    title: "Penne Arabiata",
    category: "Makarnalar",
    price: 40,
    img: "img/penne.jpg",
    desc: ``,
  },
  {
    id: 72,
    title: "Spagetti Napoliten",
    category: "Makarnalar",
    price: 40,
    img: "img/spagetti.jpg",
    desc: ``,
  },
  {
    id: 73,
    title: "Spagetti Bolognese",
    category: "Makarnalar",
    price: 50,
    img: "img/bolonez.jpg",
    desc: ``,
  },
  {
    id: 74,
    title: "Piliç Wrap",
    category: "Wraplar",
    price: 45,
    img: "img/tavukwrap.jpg",
    desc: ``,
  },
  {
    id: 75,
    title: "Çıtır Tavuk Wrap",
    category: "Wraplar",
    price: 47,
    img: "img/tavukwrap.jpg",
    desc: ``,
  },
  {
    id: 76,
    title: "Köfteli Wrap",
    category: "Wraplar",
    price: 50,
    img: "img/köfteliwrap.jpg",
    desc: ``,
  },
  {
    id: 77,
    title: "Et Wrap",
    category: "Wraplar",
    price: 55,
    img: "img/etwrap.jpg",
    desc: ``,
  },
  {
    id: 78,
    title: "Kumpir",
    category: "Kumpir",
    price: 40,
    img: "img/kumpir.jpg",
    desc: ``,
  },
  {
    id: 79,
    title: "Akdeniz Salata",
    category: "Salatalar",
    price: 30,
    img: "img/akdenizsalatası.jpg",
    desc: ``,
  },
  {
    id: 80,
    title: "Çoban Salata",
    category: "Salatalar",
    price: 32,
    img: "img/çobansalata.jpg",
    desc: ``,
  },
  {
    id: 81,
    title: "Izgara Hellim Salata",
    category: "Salatalar",
    price: 40,
    img: "img/ızgarahellim.jpg",
    desc: ``,
  },
  {
    id: 82,
    title: "Mevsim Salata",
    category: "Salatalar",
    price: 30,
    img: "img/mevsimsalata.jpg",
    desc: ``,
  },
  {
    id: 83,
    title: "Çıtır Tavuk Salata",
    category: "Salatalar",
    price: 45,
    img: "img/tavuklusezarsalata.jpg",
    desc: ``,
  },
  {
    id: 84,
    title: "Tavuklu Sezar Salata",
    category: "Salatalar",
    price: 45,
    img: "img/tavuklusezarsalata.jpg",
    desc: ``,
  },
  {
    id: 85,
    title: "Köfteli Salata",
    category: "Salatalar",
    price: 50,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 86,
    title: "Strogonof Salata",
    category: "Salatalar",
    price: 70,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 87,
    title: "Ton Balıklı Salata",
    category: "Salatalar",
    price: 45,
    img: "img/tonbalıklısalata.jpg",
    desc: ``,
  },
  {
    id: 88,
    title: "Traliçe",
    category: "Sütlü Tatlılar",
    price: 25,
    img: "img/karameliitrileçe.jpg",
    desc: ``,
  },
  {
    id: 89,
    title: "Profiterol",
    category: "Sütlü Tatlılar",
    price: 30,
    img: "img/profiterol.jpg",
    desc: ``,
  },
  {
    id: 90,
    title: "Spangle",
    category: "Sütlü Tatlılar",
    price: 30,
    img: "img/spangle.jpg",
    desc: ``,
  },
  {
    id: 91,
    title: "Sütlaç",
    category: "Sütlü Tatlılar",
    price: 30,
    img: "img/sutlac.jpg",
    desc: ``,
  },
  {
    id: 92,
    title: "Kazandibi",
    category: "Sütlü Tatlılar",
    price: 25,
    img: "img/kazandibi.jpg",
    desc: ``,
  },
  {
    id: 93,
    title: "Aşure",
    category: "Sütlü Tatlılar",
    price: 35,
    img: "img/aşure.jpg",
    desc: ``,
  },
  {
    id: 94,
    title: "Meyveli Cup",
    category: "Sütlü Tatlılar",
    price: 35,
    img: "img/meyvelicup.jpg",
    desc: ``,
  },
  {
    id: 95,
    title: "Çikolatalı Cup",
    category: "Sütlü Tatlılar",
    price: 35,
    img: "img/çikolatalıkup.jpg",
    desc: ``,
  },
  {
    id: 96,
    title: "Magnolia",
    category: "Sütlü Tatlılar",
    price: 35,
    img: "img/meyvelimag.jpg",
    desc: ``,
  },
  {
    id: 97,
    title: "Red Velved",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/redvelved.jpg",
    desc: ``,
  },
  {
    id: 98,
    title: "San Sebastian",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/sansebestian.jpg",
    desc: ``,
  },
  {
    id: 99,
    title: "Limonlu Chesee Cake",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/limonlu.jpg",
    desc: ``,
  },
  {
    id: 100,
    title: "Framboazlı Chesee Cake",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/frambuazlı.jpg",
    desc: ``,
  },
  {
    id: 101,
    title: "Fıstık Rüyası",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/fıstıkrüyası.jpg",
    desc: ``,
  },
  {
    id: 102,
    title: "Tramisu",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/tiramisu.jpg",
    desc: ``,
  },
  {
    id: 103,
    title: "Çikolatalı Kok Pasta",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/kokpasta.jph.jpg",
    desc: ``,
  },
  {
    id: 104,
    title: "Meyveli Kok Pasta",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/meyvelikök.jpg",
    desc: ``,
  },
  {
    id: 105,
    title: "Malaga",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/malaga.jpg",
    desc: ``,
  },
  {
    id: 106,
    title: "Bella Vista",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/bellavista.jpg",
    desc: ``,
  },
  {
    id: 107,
    title: "Mono Latte",
    category: "Dilim Pastalar",
    price: 35,
    img: "img/monolatte.jpg",
    desc: ``,
  },
  {
    id: 108,
    title: "Suffle",
    category: "Ek Lezzetler",
    price: 35,
    img: "img/Suffle.jpg",
    desc: ``,
  },
  {
    id: 109,
    title: "Katmer",
    category: "Ek Lezzetler",
    price: 40,
    img: "img/katmer.jpg",
    desc: ``,
  },
  {
    id: 110,
    title: "Künefe",
    category: "Ek Lezzetler",
    price: 40,
    img: "img/künefe.jpg",
    desc: ``,
  },
  {
    id: 111,
    title: "Waffle",
    category: "Ek Lezzetler",
    price: 45,
    img: "img/waffle.jpg",
    desc: ``,
  },
  {
    id: 112,
    title: "Föndü",
    category: "Ek Lezzetler",
    price: 30,
    img: "img/föndü.jpg",
    desc: ``,
  }, 
  {
    id: 113,
    title: "Ekler",
    category: "Ek Lezzetler",
    price: 30,
    img: "img/cıkolatalıekler.jpg",
    desc: ``,
  },
  {
    id: 114,
    title: "Petifür",
    category: "Ek Lezzetler",
    price: 30,
    img: "img/petifür.jpg",
    desc: ``,
  },
  {
    id: 115,
    title: "Islak Kek",
    category: "Ek Lezzetler",
    price: 30,
    img: "img/ıslakkek.jpg",
    desc: ``,
  },
  {
    id: 116,
    title: "Kuru Pasta",
    category: "Ek Lezzetler",
    price: 30,
    img: "img/kurupasta.jpg",
    desc: ``,
  },
  {
    id: 117,
    title: "Soğuk Baklava",
    category: "Baklavalar",
    price: 40,
    img: "img/sogukbaklava.jpg",
    desc: ``,
  },
  {
    id: 118,
    title: "Havuç Dilim",
    category: "Baklavalar",
    price: 40,
    img: "img/havuçdilim.jpg",
    desc: ``,
  },
  {
    id: 119,
    title: "ŞekerPare",
    category: "Baklavalar",
    price: 27,
    img: "img/şekerpare.jpg",
    desc: ``,
  },
  {
    id: 120,
    title: "Antep Sarma",
    category: "Baklavalar",
    price: 40,
    img: "img/antepsarma.jpg",
    desc: ``,
  },
  {
    id: 121,
    title: "Fıstıklı Baklava",
    category: "Baklavalar",
    price: 40,
    img: "img/fıstıklıbaklava.jpg",
    desc: ``,
  },
  {
    id: 122,
    title: "Cevizli Baklava",
    category: "Baklavalar",
    price: 40,
    img: "img/cevizlibaklava.jpg",
    desc: ``,
  },
  {
    id: 123,
    title: "Türk Kahvesi",
    category: "Kahveler",
    price: 20,
    img: "img/türkkahvesi.jpg",
    desc: ``,
  },
  {
    id: 124,
    title: " Sütlü Türk Kahvesi",
    category: "Kahveler",
    price: 22,
    img: "img/türkkahvesi.jpg",
    desc: ``,
  },
  {
    id: 125,
    title: "Damla Sakızlı Türk Kahvesi",
    category: "Kahveler",
    price: 22,
    img: "img/türkkahvesi.jpg",
    desc: ``,
  },
  {
    id: 126,
    title: "Dibek Kahvesi",
    category: "Kahveler",
    price: 22,
    img: "img/türkkahvesi.jpg",
    desc: ``,
  },
  {
    id: 127,
    title: "Menengiç",
    category: "Kahveler",
    price: 22,
    img: "img/türkkahvesi.jpg",
    desc: ``,
  },
  {
    id: 128,
    title: "Nescafe",
    category: "Kahveler",
    price: 23,
    img: "img/nescafe.jpg",
    desc: ``,
  },
  {
    id: 129,
    title: "Caffe Latte",
    category: "Kahveler",
    price: 24,
    img: "img/caffelatte.jpg",
    desc: ``,
  },
  {
    id: 130,
    title: "Aromalı Caffe Latte",
    category: "Kahveler",
    price: 26,
    img: "img/caffelatte.jpg",
    desc: `Karamelli,Çikolatalı,Fındıklı,Vanilyalı,Hindistan Cevizli`,
  },
  {
    id: 131,
    title: "Cappucino",
    category: "Kahveler",
    price: 24,
    img: "img/cap.jpg",
    desc: ``,
  },
  {
    id: 132,
    title: "Espresso",
    category: "Kahveler",
    price: 20,
    img: "img/espresso.jpg",
    desc: ``,
  },
  {
    id: 133,
    title: "Duble Espresso",
    category: "Kahveler",
    price: 26,
    img: "img/espresso.jpg",
    desc: ``,
  },
  {
    id: 134,
    title: "Mocha",
    category: "Kahveler",
    price: 24,
    img: "img/mocha.jpg",
    desc: ``,
  },
  {
    id: 135,
    title: "White Chocolate Mocha",
    category: "Kahveler",
    price: 24,
    img: "img/mocha.jpg",
    desc: ``,
  },
  {
    id: 136,
    title: "Americano",
    category: "Kahveler",
    price: 24,
    img: "img/amerika.jpg",
    desc: ``,
  },
  {
    id: 137,
    title: "Filtre Kahve",
    category: "Kahveler",
    price: 24,
    img: "img/filtrekahve.jpg",
    desc: ``,
  },
  {
    id: 138,
    title: "Sütlü Filtre Kahve",
    category: "Kahveler",
    price: 26,
    img: "img/filtrekahve.jpg",
    desc: ``,
  },
  {
    id: 139,
    title: "Sıcak Çikolata",
    category: "Sıcak Çikolatalar",
    price: 24,
    img: "img/sıcakçikolata.jpg",
    desc: ``,
  },
  {
    id: 140,
    title: "Sıcak Beyaz Çikolata",
    category: "Sıcak Çikolatalar",
    price: 25,
    img: "img/sıcakbeyazçikolata.jpg",
    desc: ``,
  },
  {
    id: 141,
    title: "Aromalı Sıcak Çikolata",
    category: "Sıcak Çikolatalar",
    price: 27,
    img: "img/aromalısıcakçikolata.jpg",
    desc: `Çilek,Karamel,Fındık`,
  },
  {
    id: 142,
    title: "Sahlep",
    category: "Sahlepler",
    price: 25,
    img: "img/sahlep.jpg",
    desc: ``,
  },
  {
    id: 143,
    title: "Aromalı Sahlep",
    category: "Sahlepler",
    price: 27,
    img: "img/sahlep.jpg",
    desc: `Çilek,Muz,Çikolata,Vanilya,Damla Sakızlı`,
  },
  {
    id: 144,
    title: "Çay",
    category: "Sıcak İçecekler",
    price: 6,
    img: "img/çay.jpg",
    desc: ``,
  },
  {
    id: 145,
    title: "Fincan Çay",
    category: "Sıcak İçecekler",
    price: 10,
    img: "img/fincançay.jpg",
    desc: ``,
  },
  {
    id: 146,
    title: "Yeşil Çay",
    category: "Sıcak İçecekler",
    price: 20,
    img: "img/yeşilçay.jpg",
    desc: ``,
  },
  {
    id: 147,
    title: "Ihlamur",
    category: "Sıcak İçecekler",
    price: 23,
    img: "img/ıhlamur.jpg",
    desc: ``,
  },
  {
    id: 148,
    title: "Nane Limon",
    category: "Sıcak İçecekler",
    price: 23,
    img: "img/nanelimon.jpg",
    desc: ``,
  },
  {
    id: 149,
    title: "Meyve Çayları",
    category: "Sıcak İçecekler",
    price: 14,
    img: "img/meyveçayları.jpg",
    desc: ``,
  },
  {
    id: 150,
    title: "Kış Çayı",
    category: "Sıcak İçecekler",
    price: 25,
    img: "img/kışçayı.jpg",
    desc: ``,
  },
  {
    id: 151,
    title: "Sıcak Süt",
    category: "Sıcak İçecekler",
    price: 13,
    img: "img/sıcaksüt.jpg",
    desc: ``,
  },
  {
    id: 152,
    title: "Delfino Şifa",
    category: "Sıcak İçecekler",
    price: 30,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 153,
    title: "Kola,Sprite,Fanta",
    category: "Soğuk İçeçekler",
    price: 15,
    img: "img/kolasprite.jpg",
    desc: ``,
  },
  {
    id: 154,
    title: "Ice Tea",
    category: "Soğuk İçeçekler",
    price: 15,
    img: "img/icetea.jpg",
    desc: ``,
  },
  {
    id: 155,
    title: "Meyve Suyu",
    category: "Soğuk İçeçekler",
    price: 15,
    img: "img/meyvesuyu.jpg",
    desc: ``,
  },
  
  {
    id: 156,
    title: "Sade Sodaa",
    category: "Soğuk İçeçekler",
    price: 10,
    img: "img/sadesoda.jpg",
    desc: ``,
  },
  {
    id: 157,
    title: "Sade Soda",
    category: "Soğuk İçeçekler",
    price: 10,
    img: "img/sadesoda.jpg",
    desc: ``,
  },
  {
    id: 158,
    title: "Meyveli Soda",
    category: "Soğuk İçeçekler",
    price: 13,
    img: "img/meyvelisoda.jpg",
    desc: ``,
  },
  {
    id: 159,
    title: "Chercull",
    category: "Soğuk İçeçekler",
    price: 15,
    img: "img/çörçil.jpg",
    desc: ``,
  },
  {
    id: 160,
    title: "Enerji İçeçeği",
    category: "Soğuk İçeçekler",
    price: 25,
    img: "img/redbul.jpg",
    desc: ``,
  },
  {
    id: 161,
    title: "Su",
    category: "Soğuk İçeçekler",
    price: 5,
    img: "img/suu.jpg",
    desc: ``,
  },
  {
    id: 162,
    title: "Cam Su",
    category: "Soğuk İçeçekler",
    price: 7,
    img: "img/camsu.jpg",
    desc: ``,
  },
  {
    id: 163,
    title: "Ayran",
    category: "Soğuk İçeçekler",
    price: 8,
    img: "img/ayran.jpg",
    desc: ``,
  },
  {
    id: 164,
    title: "Limonata",
    category: "Soğuk İçeçekler",
    price: 25,
    img: "img/limonata.jpg",
    desc: ``,
  },
  {
    id: 165,
    title: "Portakal Suyu",
    category: "Soğuk İçeçekler",
    price: 25,
    img: "img/portakalsuyu.jpg",
    desc: ``,
  },
  {
    id: 166,
    title: "Taze Mix",
    category: "Soğuk İçeçekler",
    price: 30,
    img: "img/tazemix.jpg",
    desc: ``,
  },
  {
    id: 167,
    title: "Affagato",
    category: "Buzlu İçecekler",
    price: 35,
    img: "img/affogato.jpg",
    desc: ``,
  },
  {
    id: 168,
    title: "Ice Coffe",
    category: "Buzlu İçecekler",
    price: 25,
    img: "img/icecoffe.jpg",
    desc: ``,
  },
  {
    id: 169,
    title: "Freppe",
    category: "Buzlu İçecekler",
    price: 25,
    img: "img/freppe.jpg",
    desc: ``,
  },
  {
    id: 170,
    title: "Aromalı Freppe",
    category: "Buzlu İçecekler",
    price: 27,
    img: "img/freppe.jpg",
    desc: ``,
  },
  {
    id: 171,
    title: "Ice Americano",
    category: "Buzlu İçecekler",
    price: 25,
    img: "img/ıceamerika.jpg",
    desc: ``,
  },
  {
    id: 172,
    title: "Ice Caffe Latte",
    category: "Buzlu İçecekler",
    price: 25,
    img: "img/ıcecaffe.jpg",
    desc: ``,
  },
  {
    id: 173,
    title: "Ice Mocha",
    category: "Buzlu İçecekler",
    price: 25,
    img: "img/ıcemocha.jpg",
    desc: ``,
  },
  {
    id: 174,
    title: "Çikolatalı Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/milkşake.jpg",
    desc: ``,
  },
  {
    id: 175,
    title: "Çilekli Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/çilekli.jpg",
    desc: ``,
  },
  {
    id: 176,
    title: "Muzlu Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/muzlu.jpg",
    desc: ``,
  },
  {
    id: 177,
    title: "Oreolu Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/oreolu.jpg",
    desc: ``,
  },
  {
    id: 178,
    title: "Framboazlı  Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/framboazlı.jpg",
    desc: ``,
  },
  {
    id: 179,
    title: "Karamelli Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 30,
    img: "img/karamelli.jpg",
    desc: ``,
  },
  {
    id: 180,
    title: "Kadayıf",
    category: "Baklavalar",
    price: 40,
    img: "img/kadayıf.jpg",
    desc: ``,
  },

  
  //atatürk mah papatya sok
  //sağ ve sol kırık operasyon olmuş sol bilekde açık yara dikilmiş kafes takip ediliyor 10-3
  //atakent mahallesi 221.Sokak Ege yakın sitesi  






];
const btnContainer = document.querySelector('.btn-container2');
const section = document.querySelector('.section-center');


const kategoriler = menu.reduce((values,item)=>{
  if(!values.includes(item.category)){
    values.push(item.category);
  }
  return values;
},["Hepsi"]);

const kategoriListe = ()=>{ 
  const kategoriBtn = kategoriler.map((value)=>{
  return `<option class="btn btn-outline-dark btn-item mt-2" data-id="${value}" value="${value}">${value}</option>`;
}).join('');
btnContainer.innerHTML = kategoriBtn;

btnContainer.addEventListener('change',(e)=>{
  const kategori = e.target.value;
  const menuKategori = menu.filter((menuItem)=>{
    if(menuItem.category===kategori){
      return menuItem;
    }
  }); 
  if(kategori === "Hepsi"){
    menuList(menu);
  }else{
    menuList(menuKategori);
  }
});
/*
const filterBtn = document.querySelectorAll('.btn-item');
filterBtn.forEach((btn)=>{
  btn.addEventListener('click',(e)=>{
    const kategori = e.currentTarget.dataset.id;
    const menuKategori = menu.filter((menuItem)=>{
      if(menuItem.category===kategori){
        return menuItem;
      }
    }); 
    if(kategori === "Hepsi"){
      menuList(menu);
    }else{
      menuList(menuKategori);
    }
  });
});*/
};

const menuList = (menuItems) => {
  console.log(menuItems);
  let displayMenu = menuItems.map((item) => {
    return `<div class="menu-items col-lg-6 col-sm-12">
            <img
              src=${item.img}
              alt=${item.title}
              class="photo"
            />
            <div class="menu-info">
              <div class="menu-title">
                <h4>${item.title}</h4>
                <h4 class="price">${item.price}₺</h4>
              </div>
              <div class="menu-text">
                ${item.desc}
              </div>
            </div>
          </div>
    `;
  });
  displayMenu = displayMenu.join("");
  section.innerHTML = displayMenu;
};


