const menu = [
  {
    id: 1,
    title: "Express Kahvaltı",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/express.jpg",
    desc: `Enfes Doyurucu BOL Kahvaltı.`,
  },
  {
    id: 2,
    title: "Tek Kişilik Tabak",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/tek.jpg",
    desc: `Tek Kişilik Kahvaltı Tabağı. `,
  },
  {
    id: 3,
    title: "Börekli Kahvaltı",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/börek.jpg",
    desc: `Börekli Kahvaltı Tabağı`,
  },
  {
    id: 4,
    title: "Delfino Kahvaltı Tabağı",
    category: "Kahvaltılıklar",
    price: 00,
    img: "",
    desc: `Delfino Kahvaltı Tabağı İle Lezzeti Doruklarda Yaşayın. `,
  },
  {
    id: 5,
    title: "Serpme Kahvaltı",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/express.jpg",
    desc: `Serpme Kahvaltının Tadını Çıkartın`,
  },
  {
    id: 6,
    title: "Sıcak Simit Tabağı",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/simit.jpg",
    desc: `Sıcak Simitin Tadını Çıkartın`,
  },
  {
    id: 7,
    title: "Kol Böreği",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/kol.jpg",
    desc: `Kıymalı,Peynirli,Patetesli`,
  },
  {
    id: 8,
    title: "Su Böreği",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/su.jpg",
    desc: `Sıcak Ve Taze Su Böreği`,
  },
  {
    id: 9,
    title: "Gül Böreği",
    category: "Kahvaltılıklar",
    price: 00,
    img: "img/gül.jpg",
    desc: `Sıcak Ve Taze Gül Böreği.`,
  },
  {
    id: 10,
    title: "Sahanda Yumurta",
    category: "Omlet Ve Menemen",
    categoryname: "Omlet Ve Menemen",
    price: 00,
    img: "img/sahanda.jpg",
    desc: `Sahanda Sucuklu 00TL , Sahanda Kaşarlı 00TL , Sahanda Kaşarlı 00TL , Sahanda Kavurmalı 00TL , Sahanda Karışık 00TL`,
  },
  {
    id: 11,
    title: "Omletler",
    category: "Omlet Ve Menemen",
    price: 00,
    img: "img/omlet.jpg",
    desc: `Sade Omlet 00TL , Kaşarlı Omlet 00TL , Sucuklu Omlet 00TL , Sebzeli Omlet 00TL , Kavurmalı Omlet 00TL`,
  },
  {
    id: 12,
    title: "Menemen",
    category: "Omlet Ve Menemen",
    price: 00,
    img: "img/menemen.jpg",
    desc: `Sade Menemen 00TL , Kaşarlı Menemen 00TL , Sucuklu Menemen 00TL , Karışık Menemen 00TL , Kavurmalı Menemen 00TL`,
  },
  {
    id: 13,
    title: "Mıhlama",
    category: "Omlet Ve Menemen",
    price: 00,
    img: "img/mıhlama.jpg",
    desc: ``,
  },
  {
    id: 14,
    title: "Günün Çorbası",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 15,
    title: "Günün Menüsü",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 16,
    title: "Yumurtalı Ekmek",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 17,
    title: "Sosis Tabağı",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 18,
    title: "Delfino Tabağı",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 19,
    title: "Paçanga Böreği",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 20,
    title: "Soğan Halkası",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 21,
    title: "Parmak Patetes",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 22,
    title: "Elma Dilim Patetes",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 23,
    title: "Çıtır Tavuk Parçaları",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 24,
    title: "Nugget",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 25,
    title: "Karışık Pizza",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: `Orta Boy`,
  },
  {
    id: 26,
    title: "Mantı",
    category: "Aperatifler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 27,
    title: "Ton Balıklı Sandviç",
    category: "Sandviç",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 28,
    title: "Karışık Sandviç",
    category: "Sandviç",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 29,
    title: "Tavuklu Sandviç",
    category: "Sandviç",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 30,
    title: "Köfteli Sandviç",
    category: "Sandviç",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 31,
    title: "Beyaz Peynirli Sandviç",
    category: "Sandviç",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 32,
    title: "Kaşarlı Tost",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 33,
    title: "Sucuklu Tost",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 34,
    title: "Beyaz Peynir Domates Tost",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 35,
    title: "Karışık Tost",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 36,
    title: "Kavurmalı Tost",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 37,
    title: "Ayvacık Tostu",
    category: "Tost",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 38,
    title: "Kaşarlı Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 39,
    title: "Sucuklu Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 40,
    title: "Peynirli Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 41,
    title: "Patatesli Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 42,
    title: "Kavurmalı Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 43,
    title: "Kıymalı Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 44,
    title: "Karışık Gözleme Gözleme",
    category: "Gözleme",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 45,
    title: "Tavuk Sote",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 46,
    title: "Güveçte Kaşarlı Tavuk Sote",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 47,
    title: "Güveçte Kaşarlı Et Sote",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 48,
    title: "Köri Soslu Tavuk",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 49,
    title: "Mantarlı Tavuk Sote",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 50,
    title: "Kremalı Mantarlı Tavuk",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 51,
    title: "Tavuk Pirzola Bonfile",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 52,
    title: "Viyana Schinitzel",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 53,
    title: "Et Sote",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 54,
    title: "Fajita Chicken",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 55,
    title: "Fajita Steak",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 56,
    title: "Izgara Kasap Köfte",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 57,
    title: "Kaşarlı Kasap Köfte",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 58,
    title: "Izgara Piliç Şiş",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 59,
    title: "Izgara Et Çöp Şiş",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 60,
    title: "Izgara Steak",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 61,
    title: "Karışık Izgara",
    category: "Ana Yemekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 62,
    title: "DELFİNO Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 63,
    title: "Steak Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 64,
    title: "Mini Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 65,
    title: "Cheese Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 66,
    title: "DELFİNO Tavuk Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },{
    id: 67,
    title: "Tavuk Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 68,
    title: "Mini Tavuk Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 69,
    title: "Tavuk Cheese Burger",
    category: "Burgerler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 70,
    title: "Fettucine Alfredo",
    category: "Makarnalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 71,
    title: "Penne Arabiata",
    category: "Makarnalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 72,
    title: "Spagetti Napoliten",
    category: "Makarnalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 73,
    title: "Spagetti Bolognese",
    category: "Makarnalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 74,
    title: "Piliç Wrap",
    category: "Wraplar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 75,
    title: "Çıtır Tavuk Wrap",
    category: "Wraplar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 76,
    title: "Köfteli Wrap",
    category: "Wraplar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 77,
    title: "Et Wrap",
    category: "Wraplar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 78,
    title: "Kumpir",
    category: "Kumpir",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 79,
    title: "Akdeniz Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 80,
    title: "Çoban Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 81,
    title: "Izgara Hellim Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 82,
    title: "Mevsim Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 83,
    title: "Çıtır Tavuk Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 84,
    title: "Sezar Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 85,
    title: "Köfteli Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 86,
    title: "Strogonof Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 87,
    title: "Ton Balıklı Salata",
    category: "Salatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 88,
    title: "Traliçe",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 89,
    title: "Profiterol",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 90,
    title: "Spangle",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 91,
    title: "Sütlaç",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 92,
    title: "Kazandibi",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 93,
    title: "Aşure",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 94,
    title: "Meyveli Cup",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 95,
    title: "Çikolatalı Cup",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 96,
    title: "Magnolia",
    category: "Sütlü Tatlılar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 97,
    title: "Red Velved",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 98,
    title: "San Sebastian",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 99,
    title: "Limonlu Chesee Cake",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 100,
    title: "Framboazlı Chesee Cake",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 101,
    title: "Fıstık Rüyası",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 102,
    title: "Tramisu",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 103,
    title: "Çikolatalı Kok Pasta",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 104,
    title: "Meyveli Kok",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 105,
    title: "Malaga",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 106,
    title: "Bella Vista",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 107,
    title: "Mono Latte",
    category: "Dilim Pastalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 108,
    title: "Suffle",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 109,
    title: "Katmer",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 110,
    title: "Künefe",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 111,
    title: "Waffle",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 112,
    title: "Föndü",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  }, 
  {
    id: 113,
    title: "Ekler",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 114,
    title: "Petifür",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 115,
    title: "Islak Kek",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 116,
    title: "Kuru Pasta",
    category: "Ek Lezzetler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 117,
    title: "Soğuk Baklava",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 118,
    title: "Havuç Dilim",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 119,
    title: "ŞekerPare",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 120,
    title: "Antep Sarma",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 121,
    title: "Fıstıklı Baklava",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 122,
    title: "Cevizli Baklava",
    category: "Baklavalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 123,
    title: "Türk Kahvesi",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 124,
    title: " Sütlü Türk Kahvesi",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 125,
    title: "Damla Sakızlı Türk Kahvesi",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 126,
    title: "Dibek Kahvesi",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 127,
    title: "Menengiç",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 128,
    title: "Nescafe",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 129,
    title: "Caffe Latte",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 130,
    title: "Aromalı Caffe Latte",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: `Karamelli,Çikolatalı,Fındıklı,Vanilyalı,Hindistan Cevizli`,
  },
  {
    id: 131,
    title: "Cappucino",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 132,
    title: "Espresso",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 133,
    title: "Duble Espresso",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 134,
    title: "Mocha",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 135,
    title: "White Chocolate Mocha",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 136,
    title: "Americano",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 137,
    title: "Filtre Kahve",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 138,
    title: "Sütlü Filtre Kahve",
    category: "Kahveler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 139,
    title: "Sıcak Çikolata",
    category: "Sıcak Çikolatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 140,
    title: "Sıcak Beyaz Çikolata",
    category: "Sıcak Çikolatalar",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 141,
    title: "Aromalı Sıcak Çikolata",
    category: "Sıcak Çikolatalar",
    price: 00,
    img: "img/.jpg",
    desc: `Çilek,Karamel,Fındık`,
  },
  {
    id: 142,
    title: "Sahlep",
    category: "Sahlepler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 143,
    title: "Aromalı Sahlep",
    category: "Sahlepler",
    price: 00,
    img: "img/.jpg",
    desc: `Çilek,Muz,Çikolata,Vanilya,Damla Sakızlı`,
  },
  {
    id: 144,
    title: "Çay",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 145,
    title: "Fincan Çay",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 146,
    title: "Yeşil Çay",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 147,
    title: "Ihlamur",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 148,
    title: "Nane Limon",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 149,
    title: "Meyve Çayları",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 150,
    title: "Kış Çayı",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 151,
    title: "Sıcak Süt",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 152,
    title: "Delfino Şifa",
    category: "Sıcak İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 153,
    title: "Kola,Sprite,Fanta",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 154,
    title: "Ice Tea",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 155,
    title: "Meyve Suyu",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 156,
    title: "Kola,Sprite,Fanta",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 157,
    title: "Sade Soda",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 158,
    title: "Meyveli Soda",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 159,
    title: "Chercull",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 160,
    title: "Enerji İçeçeği",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 161,
    title: "Su",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 162,
    title: "Cam Su",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 163,
    title: "Ayran",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 164,
    title: "Limonata",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 165,
    title: "Portakal Suyu",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 166,
    title: "Taze Mix",
    category: "Soğuk İçeçekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 167,
    title: "Affagato",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 168,
    title: "Ice Coffe",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 169,
    title: "Freppe",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 170,
    title: "Aromalı Freppe",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 171,
    title: "Ice Americano",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 172,
    title: "Ice Caffe Latte",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 173,
    title: "Ice Mocha",
    category: "Buzlu İçecekler",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 174,
    title: "Çikolatalı Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 175,
    title: "Çilekli Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 176,
    title: "Muzlu Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 177,
    title: "Oreolu Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 178,
    title: "Framboazlı  Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },
  {
    id: 179,
    title: "Karamelli Milkshake",
    category: "Mılhkshake,Smotıe,Frozen",
    price: 00,
    img: "img/.jpg",
    desc: ``,
  },

  
  //atatürk mah papatya sok
  //sağ ve sol kırık operasyon olmuş sol bilekde açık yara dikilmiş kafes takip ediliyor 10-3
  //atakent mahallesi 221.Sokak Ege yakın sitesi  






];
const btnContainer = document.querySelector('.btn-container2');
const section = document.querySelector('.section-center');


const kategoriler = menu.reduce((values,item)=>{
  if(!values.includes(item.category)){
    values.push(item.category);
  }
  return values;
},["Hepsi"]);

const kategoriListe = ()=>{ 
  const kategoriBtn = kategoriler.map((value)=>{
  return `<option class="btn btn-outline-dark btn-item mt-2" data-id="${value}" value="${value}">${value}</option>`;
}).join('');
btnContainer.innerHTML = kategoriBtn;


const filterBtn = document.querySelectorAll('.btn-item');
filterBtn.forEach((btn)=>{
  btn.addEventListener('click',(e)=>{
    const kategori = e.currentTarget.dataset.id;
    const menuKategori = menu.filter((menuItem)=>{
      if(menuItem.category===kategori){
        return menuItem;
      }
    }); 
    if(kategori === "Hepsi"){
      menuList(menu);
    }else{
      menuList(menuKategori);
    }
  });
});
};

const menuList = (menuItems) => {
  console.log(menuItems);
  let displayMenu = menuItems.map((item) => {
    return `<div class="menu-items col-lg-6 col-sm-12">
            <img
              src=${item.img}
              alt=${item.title}
              class="photo"
            />
            <div class="menu-info">
              <div class="menu-title">
                <h4>${item.title}</h4>
                <h4 class="price">${item.price}₺</h4>
              </div>
              <div class="menu-text">
                ${item.desc}
              </div>
            </div>
          </div>
    `;
  });
  displayMenu = displayMenu.join("");
  section.innerHTML = displayMenu;
};

menuList(menu);
kategoriListe();

